USE TallaEggOrders;

CREATE TABLE Orders (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Asset NVARCHAR(100) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Price DECIMAL(18,2) NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Type NVARCHAR(10) NOT NULL,
    CreatedAt DATETIME2 NOT NULL
); 